import img1 from './assets/images/img1.png'
import img2 from './assets/images/img2.jpg'
import img3 from './assets/images/img3.jpg'
import img4 from './assets/images/img4.jpg'
import img5 from './assets/images/img5.jpg'
import img6 from './assets/images/img6.jpg'
import img7 from './assets/images/img7.jpg'
import img8 from './assets/images/img8.jpg'
import img9 from './assets/images/img9.jpg'
import img10 from './assets/images/img10.jpg'

import img11 from './assets/images/meeting/img1.jpg'
import img12 from './assets/images/meeting/img2.jpg'
import img13 from './assets/images/meeting/img3.jpg'
import img14 from './assets/images/meeting/img4.jpg'
import img15 from './assets/images/meeting/img5.jpg'
import img16 from './assets/images/meeting/img6.jpg'
import img17 from './assets/images/meeting/img7.jpg'
import img18 from './assets/images/meeting/img8.jpg'
import img19 from './assets/images/meeting/img9.jpg'
import img20 from './assets/images/meeting/img10.jpg'


export const nikahs = [
    {id: "1", 
    name: 'Asha Juma', 
    url: img1,  
    live: 'Tanga', 
    tribe: 'Zaramo', 
    age:'25', 
    education: 'Bachelor', 
    quran: 'Juzuu Amma', 
    height: '175cm', 
    weight:'55kg', 
    prayer: 'Sometimes',
    body:'Slim', 
    emmployement: 'self employee',
    blood: 'Group C+',
    occupation:'Student',
    child:'No',
    status:'Single',
    stays: 'Manzese',
    Ethnicity: 'Black',
    religion_set:'Sunni',
    gender:'Male',
    islam_by: 'Birth'
},
{id: "2", 
name: 'Moza Juma', 
url: img2,  
live: 'Dar es Salaam', 
tribe: 'Chaga', 
prayer: 'Sometimes',
age:'30', 
education: 'Certifcate', 
quran: 'Alfatiha', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'Computer',
child:'No',
stays: 'Manzese',
Ethnicity: 'Indian',
religion_set:'Salaf',
status:'Single',
islam_by: 'Birth',
gender:'Female',
},
{id: "3", 
name: 'Arha Ally', 
url: img3,  
live: 'With Friends', 
prayer: 'Sometimes',

tribe: 'Zaramo', 
age:'20', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'Computer',
child:'Yes',
stays: 'Manzese',
Ethnicity: 'Black',
status:'Single',
islam_by: 'Birth',
religion_set:'Sunni',
gender:'Male',
},
{id: "4", 
name: 'Asha Juma', 
url: img4,  
live: 'With Family', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
status:'Single',
blood: 'Group C+',
occupation:'Student',
child:'No',
islam_by: 'Birth',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "5", 
name: 'Asha Juma', 
url: img5,  
live: 'Alone', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
islam_by: 'Birth',
body:'Slim', 
prayer: 'Sometimes',

emmployement: 'self employee',
status:'Single',
blood: 'Group C+',
occupation:'Student',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "6", 
name: 'Asha Juma', 
url: img6,  
islam_by: 'Birth',
live: 'With family', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
status:'Single',
occupation:'Student',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "7", 
name: 'Asha Juma', 
url: img7,  
live: 'Alone', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
status:'Single',
occupation:'Student',
child:'No',
prayer: 'Sometimes',
stays: 'Manzese',
Ethnicity: 'Black',
islam_by: 'Birth',
religion_set:'Sunni',
gender:'Male',
},
{id: "8", 
name: 'Asha Juma', 
url: img8,  
live: 'Tanga', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group C+',
occupation:'Student',
islam_by: 'Birth',
prayer: 'Sometimes',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
status:'Single',
gender:'Male',
},
{id: "9", 
name: 'Asha Juma', 
url: img1,  
live: 'Tanga', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
islam_by: 'Revert',
prayer: 'Sometimes',
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group C+',
occupation:'Student',
child:'No',
status:'Single',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "10", 
name: 'Asha Juma', 
url: img10,  
live: 'Tanga', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
prayer: 'Sometimes',
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
islam_by: 'Birth',
occupation:'Student',
child:'No',
status:'Single',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "11", 
name: 'Asha Juma', 
url: img8,  
live: 'Tanga', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
prayer: 'Sometimes',
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
islam_by: 'Revert',
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'Student',
child:'No',
status:'Single',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "12", 
name: 'Asha Juma', 
url: img7,  
live: 'Tanga', 
tribe: 'Zaramo', 
prayer: 'Sometimes',
islam_by: 'Birth',
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 

body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
status:'Single',
occupation:'Student',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "13", 
name: 'Asha Juma', 
url: img9,  
live: 'Alone', 
tribe: 'Zaramo', 
age:'25', 
education: 'Bachelor', 
quran: 'Juzuu Amma', 
status:'Single',
height: '175cm', 
weight:'55kg', 
prayer: 'Sometimes',
islam_by: 'Revert',
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'Student',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "15", 
name: 'Asha Juma', 
url: img6,  
live: 'Tanga', 
tribe: 'Zaramo', 
prayer: 'Sometimes',
age:'25', 
education: 'Bachelor',
status:'Single', 
quran: 'Juzuu Amma', 
height: '175cm', 
islam_by: 'Birth',
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'Student',
child:'No',
stays: 'Manzese',
Ethnicity: 'Black',
religion_set:'Sunni',
gender:'Male',
},
{id: "16", 
name: 'Asha Juma', 
url: img4,  
live: 'With friends', 
prayer: 'Sometimes',
tribe: 'Zaramo', 
islam_by: 'Revert',
age:'25', 
status:'Single',
education: 'Bachelor', 
quran: 'Juzuu Amma', 
height: '175cm', 
weight:'55kg', 
body:'Slim', 
emmployement: 'self employee',
blood: 'Group A',
occupation:'NA',
child:'NA',
stays: 'NA',
Ethnicity: 'NA',
religion_set:'NA',
gender:'NA',
},
]

export const meetings = [
    {name: 'Rashid Omary', url: img11},
    {name: 'Omary Hassan', url: img12},
    {name: 'Baraka Omary', url: img13},
    {name: 'Saidia Juma', url: img14},
    {name: 'Omary Shamte', url: img15},
    {name: 'Azam Tv', url: img16},
    {name: 'Mwandonga Rashid', url: img17},
    {name: 'Peter Juma', url: img18},
    {name: 'Aliya Ally', url: img19},
    {name: 'You', url: img20},

]

export const ages = ['18','19','20','21', '22', '23','24','25','26','27','28','29','30','31','32','33','34','35','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90']

export const heights = ['110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163','164','165','166','167','168','169','170','171','172','173','174','175','176','177','178','179','180','181','182','183','184','185','186','187','188','189','190','191','192','193','194','195','196','197','198','199','200']

export const weight = ['40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','98','90','91','92','93','94','95','96','97','98','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130']

export const tribes = ['Alagwa','Akiek','Akie ','Arusha','Assa','Barabaig','Balouch','Bembe','Bena','Bende','Bondei','Bungu','Burunge','Chaga','Datooga','Dhaiso','Digo','Doe','Fipa','Gogo','Goa','Goma','Gorowa','Gujarati','Gweno','Ha','Hutu','Hadza','Hangaza','Haya','Hehe','Holoholo','Hutu','Ikizu','Ikoma','Iraqw','Isanzu','Jiji','Jita','Kabwa','Kagura','Kaguru','Kahe','Kami','Kamba','Kara','Kerewe','Kikuyu','Kimbu','Kinga','Kisankasa','Kisi','Konongo','Kuria','Kutu','Kwadza','Kwavi','Kwaya','Kwere','Kwifa','Lambya','Luguru','Lungu','Luo','Maasai','Machinga','Magoma','Mahanji','Mbulu','Makonde','Makua','Makwe','Mambwe','Manyema','Manda','Mahara','Mediak','Meru','Matengo','Matumbi','Maviha','Mbugwe','Mbunga','Mbugu','Mosiro','Mpoto','Msur','Mwanga','Mwera','Natta','Ndali','Ndamba','Ndendeule','Ndengereko','Ndonde','Nyanja','Ngas','Ngasa','Ngindo','Ngoni','Ngulu','Ngazija','Ngurimi','Ngwele','Nilamba','Nindi','Nyakyusa','Nyasa','Nyambo','Nyamwanga','Nyamwezi','Nyanyembe','Nyaturu','Nyiha','Nyiramba','Omotik','Okiek','Pangwa','Pare','Pimbwe','Pogolo','Rangi','Rufiji','Rungi','Rungwa','Rwa','Safwa','Sagara','Sandawe','Sangu','Segeju','Swengwear','Shambaa','Shirazi','Shubi','Sizaki','Suba','Sukuma','Sumbwa','Sungu','Swahili','Temi','Tongwe','Twa','Tutsi','Tumbuka','Vidunda','Vinza','Wanda','Washihiri','Wamanga','Wanji','Ware','Yaaku','Yao','Zanaki','Zaramo','Zigua','Zinza','Zyoba','Zulu']